package com.cap10mycap10.murikaztenders.model;


public enum ServiceType {

    BASELINE_EVALUATION,
    SOCIO_ECONOMIC_SURVEY,
    FEASIBILITY_STUDY,
    INSTITUTIONAL_CAPACITY_ASSESSMENT,
    FORMULATION_OF_POLICIES_AND_COSTED_PLANS,
    DESIGN_OF_PROGRAMS_AND_PROJECTS,
    MANAGEMENT_OF_DONOR_PROJECTS,
    CAPACITY_BUILIDING,
    DESIGN_AND_IMPLEMENTATION_OF_MNE_SYSTEMS,
    IMPACT_EVALUATION_DEVELOPMENT_PROJECTS,
    VALUE_FOR_MONEY_ASSESSMENTS,
    WORKSHOP_FACILITATION


}
