package com.cap10mycap10.murikaztenders.model;


public enum Thematic {
    EDUCATION,
    AGRICULTURE_AND_FOOD_SECURITY,
    AID_EFFECTIVENESS_AND_RBM,
    CHILDREN_AND_YOUTH,
    ENERGY,
    ENVIRONMENT_AND_CLIMATE,
    GENDER,
    GOVERNANCE,
    HEALTH_HIV_AND_AIDS,
    ICT,
    NATURAL_RESOURCES_MANAGEMENT,
    NUTRITION,
    ORGANISATIONAL_DEVELOPMENT,
    POVERTY_AND_SOCIAL_PROTECTION,
    TRANSPORT_AND_ROAD_INFRASTRUCTURE,
    WASH
}
